---
title: "Workflow POW"
output:
  "BiocStyle::html_document":
    dev: png
  "BiocStyle::pdf_document":
    latex_engine: lualatex
    df_print: "kable"
    dev: png
package: pow
date: "`r format(Sys.Date(), '%F')`"
abstract: >
  An introduction to the workflow to optimize and apply the POW algotithm to a
  dataset
vignette: >
  %\VignetteIndexEntry{Workflow_POW}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pow)
library(ggplot2)
library(BiocParallel)
```


```{r }
# Enable parallelization, to make it faster you can increase workers up to the
# number of cores available.
register(SnowParam(workers = 2, 
                   progressbar =interactive() && 
                     is.null(getOption("knitr.in.progress")), 
                   exportglobals = FALSE), 
         default = TRUE)
```

```{r load ketones}
# library(GCIMS)
# samples_directory<- "/storage/projects/TargetML/KETONES"
# annotations <- read.csv(file.path(samples_directory,"annotations.csv"))
# annotations <- annotations[-c(26,27,32,34,36,37,38),]
# dataset1 <- GCIMSDataset$new(
#   annotations,
#   base_dir = samples_directory,
#   on_ram = FALSE
# )
# filterRt(dataset1, rt = c(0, 1500)) # in s
# filterDt(dataset1, dt = c(5, 16)) # in ms
# dataset1 <- smooth(dataset1, rt_length_s = 3, dt_length_ms = 0.14)
# decimate(dataset1, rt_factor = 1, dt_factor = 2)
# align_ip(dataset1)
# dataset1$realize()
# data <- dataset1$getRIC()
```

```{r}
set.seed(100)
data <- synthetic_dataset(n_samples = 15,
                          n_peaks = 10,
                          length_out = 1500,
                          mov_peaks = 5,
                          intensity = 500,
                          random_intensity = 50)
```

```{r}
idx_y <- select_reference(data)
X <- as.matrix(data[-idx_y, ])
y <- as.matrix(data[idx_y, ])
n_samples <- nrow(X)
m <- length(y)
v <- rep(1, m)
iv <- seq(2, m - 1, by = 10)
v[iv] <- 0
W <- Matrix::Diagonal(x = v)
```

```{r}
lambdas <- pracma::logspace(-3, 5, 128)
val <- compute_val_error(X, y, W, iv, lambdas)
opar <- optimize_params(n_samples, lambdas, val$ti_ix, val$e_ix)
best_lambdas2 <- opar$best_params
```

```{r}
XW <- apply_pow(X, best_lambdas2, y)
```

```{r}
df_raw <- data.frame(t(X))
df_raw <- cbind(df_raw ,Time = c(1:nrow(df_raw)))
df_raw <- reshape2::melt(df_raw, "Time")
raw_data <- ggplot(data = df_raw, aes(x = Time, y = value, col = variable)) +
  geom_line() +
  ylab("Intensity") +
  guides(colour = "none")

df_pow <- data.frame(t(XW))
df_pow <- cbind(df_pow,Time = c(1:nrow(df_pow)))
df_pow <- reshape2::melt(df_pow, "Time")
pow_data <- ggplot(data = df_pow, aes(x = Time, y = value, col = variable)) + 
  geom_line() +
  ylab("Intensity") +
  guides(colour = "none")

cowplot::plot_grid(raw_data,pow_data)
```

```{r}
image(c(1:m), 
      c(1:nrow(XW)), 
      t(XW), 
      col = hcl.colors(10, "Grays"),  
      xlab = "Time", 
      ylab = "Sample") + 
  title("Image of aligned Spectra with POW")
```

```{r}
image(c(1:m), 
      c(1:nrow(X)), 
      t(X), 
      col = hcl.colors(10, "Grays"),  
      xlab = "Time", 
      ylab = "Sample") + 
  title("Image of Raw Samples")
```
